version: '3'

services:
  airflow-webserver:
    image: apache/airflow:3.0.0
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/etl
      - ./data:/opt/data
      - ./airflow_db:/opt/airflow
      - ./output:/opt/output
    ports:
      - "8081:8080"           # Airflow UI at localhost:8081
    command: api-server       # Updated for Airflow 3.0
 

  airflow-scheduler:
    image: apache/airflow:3.0.0 
    bulid:     
    restart: always
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/etl
      - ./data:/opt/data
      - ./airflow_db:/opt/airflow
    command: scheduler

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8082:8081"

