version: '3'

services:
  airflow:
    image: apache/airflow:2.7.2
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl_pipeline:/opt/etl
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - spark

  spark:
    image: bitnami/spark:latest
    container_name: spark
    ports:
      - "4040:4040"
