version: '3'

services:
  airflow-webserver:
    image: apache/airflow:3.0.0
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/etl
      - ./data:/opt/data
      - ./airflow_db:/opt/airflow
      - ./output:/opt/output
    ports:
      - "8081:8080"           # Airflow UI at localhost:8081
    command: api-server       # Updated for Airflow 3.0
    entrypoint: >
      bash -c "
        airflow db migrate &&
        airflow users create --username airflow --password airflow --firstname admin --lastname user --role Admin --email
 




    


